[package]
name = "simple_gui"
version = "0.1.0"
authors = ["Gianfranco Dutka <gdutk007@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orbtk = "0.3.1-alpha1"
